port: 7880
rtc_port: 7881
log_level: debug
rtc:
  udp_port_range: "50000-60000"
  tcp_port: 7881
  use_external_ip: true
  # Указываем внешний IP для ICE candidates
  ice_servers:
    - urls: stun:stun.l.google.com:19302
keys:
  APIdL717D1nEfC0: rRf7KDspB3inmBQNCX2Nf1EgLKDmJ6xngqhYrPm8w0A
